<?php

/**
 * @param array $element
 * @param array|bool $input
 * @param array $form_state
 *
 * @return array|int|null
 *
 * @see \Drupal\cfrfamily\ConfToForm\ConfToForm_CfrLegendExpanded::confGetForm()
 */
function _cfrfamily_value_callback($element, $input = FALSE, array $form_state = array()) {

  if ($input !== FALSE) {
    # dpm($input, 'INPUT');
    $optionsConf = isset($input['options'])
      ? $input['options']
      : NULL;
    if (isset($input['id']) && is_string($input['id'])) {
      $combinedIdDecoded = json_decode($input['id'], FALSE, 2);
      if (is_string($combinedIdDecoded)) {
        return array(
          'id' => $combinedIdDecoded,
          'options' => $optionsConf,
        );
      }
      elseif (is_array($combinedIdDecoded) && $combinedIdDecoded === array_values($combinedIdDecoded)) {
        while (NULL !== $deepestId = array_pop($combinedIdDecoded)) {
          if (!is_string($deepestId)) {
            return NULL;
          }
          $optionsConf = array(
            'id' => $deepestId,
            'options' => $optionsConf,
          );
        }
        return $optionsConf;
      }
      else {
        return NULL;
      }
    }
    return NULL;
  }
  elseif (isset($element['#default_value'])) {
    # dpm($element['#default_value'], 'DEFAULT VALUE');
    return $element['#default_value'];
  }
  else {
    if (isset($form_state['values'])) {
      # dpm($form_state['values']);
    }
    return 0;
  }
}

