<?php

use Drupal\cfrplugin\Hub\CfrPluginHub;

/**
 * @return \Drupal\cfrplugin\Hub\CfrPluginHubInterface
 */
function cfrplugin() {
  static $hub;
  return isset($hub)
    ? $hub
    : $hub = CfrPluginHub::create();
}

/**
 * Implements hook_permission().
 */
function cfrplugin_permission() {
  return [
    'view cfrplugin report' =>  [
      'title' => t('View report of Cfr plugins'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function cfrplugin_menu() {
  $items = [];
  $items['admin/reports/cfrplugin'] = [
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => ['view cfrplugin report'],
    'title' => 'Cfr plugins',
    /* @see _cfrplugin_report_page() */
    'page callback' => '_cfrplugin_report_page',
    'file' => 'cfrplugin.page.report.inc',
  ];
  return $items;
}

/**
 * Implements hook_admin_menu_cache_info()
 *
 * @return array[]
 */
function cfrplugin_admin_menu_cache_info() {

  $caches['cfrplugin_info'] = [
    'title' => t('Cfr plugin info'),
    /* @see _cfrplugin_info_cache_clear() */
    'callback' => '_cfrplugin_info_cache_clear',
  ];

  return $caches;
}

/**
 * Callback for admin_menu cache clearing.
 */
function _cfrplugin_info_cache_clear() {
  cache_clear_all('cfrplugin:', 'cache', TRUE);
}
