<?php

use Drupal\cfrplugin\Hub\CfrPluginHub;

require_once __DIR__ . '/cfrplugin.form_element.inc';
require_once __DIR__ . '/cfrplugin.menu.inc';

/**
 * @return \Drupal\cfrplugin\Hub\CfrPluginHubInterface
 */
function cfrplugin() {
  static $hub;
  return NULL !== $hub
    ? $hub
    : $hub = CfrPluginHub::create();
}

/**
 * Implements hook_permission().
 *
 * @return array[]
 */
function cfrplugin_permission() {
  return [
    'view cfrplugin report' =>  [
      'title' => t('View report of Cfr plugins'),
      'restrict access' => TRUE,
      'warning' => t('The report page might reveal some implementation details.'),
    ],
  ];
}

/**
 * Implements hook_admin_menu_cache_info()
 *
 * @return array[]
 */
function cfrplugin_admin_menu_cache_info() {

  $caches['cfrplugin_info'] = [
    'title' => t('Cfr plugin info'),
    /* @see _cfrplugin_info_cache_clear() */
    'callback' => '_cfrplugin_info_cache_clear',
  ];

  return $caches;
}

/**
 * Callback for admin_menu cache clearing.
 */
function _cfrplugin_info_cache_clear() {
  if (NULL !== $cacheSection = CfrPluginHub::getContainer()->cacheRootOrNull) {
    $cacheSection->clear();
  }
}
